version: "1.1"
services:
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5173:5173
  db:
    image: postgres:latest
    container_name: postgres_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: # todo: get from .env
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432 # Publishes 5433 to other containers but NOT to host machine
#    command:
#      - -p 5433
volumes:
  postgres_data: