services:
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5173:5173
  db:
    image: postgres:latest
    container_name: postgres_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: # todo: get from .env
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      #- POSTGRES_DB=admin
    #restart: always
    ports:
      - 5433:5433
volumes:
  postgres_data:
    external: false